/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import { Context } from './context'
import { core, connectionPluginCore } from 'nexus'

declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName>,
    ): void
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BooleanFilter: {
    // input type
    equals?: boolean | null // Boolean
    not?: boolean | null // Boolean
  }
  CollectionCreateManyWithoutOwnerInput: {
    // input type
    connect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
    create?: NexusGenInputs['CollectionCreateWithoutOwnerInput'][] | null // [CollectionCreateWithoutOwnerInput!]
  }
  CollectionCreateManyWithoutSectionInput: {
    // input type
    connect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
    create?: NexusGenInputs['CollectionCreateWithoutSectionInput'][] | null // [CollectionCreateWithoutSectionInput!]
  }
  CollectionCreateOneWithoutItemsInput: {
    // input type
    connect?: NexusGenInputs['CollectionWhereUniqueInput'] | null // CollectionWhereUniqueInput
    create?: NexusGenInputs['CollectionCreateWithoutItemsInput'] | null // CollectionCreateWithoutItemsInput
  }
  CollectionCreateWithoutItemsInput: {
    // input type
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    detail?: string | null // String
    id?: string | null // String
    isDeleted?: boolean | null // Boolean
    name?: string | null // String
    owner: NexusGenInputs['UserCreateOneWithoutCollectionsInput'] // UserCreateOneWithoutCollectionsInput!
    section: NexusGenInputs['SectionCreateOneWithoutCollectionsInput'] // SectionCreateOneWithoutCollectionsInput!
    slug: string // String!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  CollectionCreateWithoutOwnerInput: {
    // input type
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    detail?: string | null // String
    id?: string | null // String
    isDeleted?: boolean | null // Boolean
    items?: NexusGenInputs['ItemCreateManyWithoutCollectionInput'] | null // ItemCreateManyWithoutCollectionInput
    name?: string | null // String
    section: NexusGenInputs['SectionCreateOneWithoutCollectionsInput'] // SectionCreateOneWithoutCollectionsInput!
    slug: string // String!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  CollectionCreateWithoutSectionInput: {
    // input type
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    detail?: string | null // String
    id?: string | null // String
    isDeleted?: boolean | null // Boolean
    items?: NexusGenInputs['ItemCreateManyWithoutCollectionInput'] | null // ItemCreateManyWithoutCollectionInput
    name?: string | null // String
    owner: NexusGenInputs['UserCreateOneWithoutCollectionsInput'] // UserCreateOneWithoutCollectionsInput!
    slug: string // String!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  CollectionFilter: {
    // input type
    every?: NexusGenInputs['CollectionWhereInput'] | null // CollectionWhereInput
    none?: NexusGenInputs['CollectionWhereInput'] | null // CollectionWhereInput
    some?: NexusGenInputs['CollectionWhereInput'] | null // CollectionWhereInput
  }
  CollectionItemsOrderByInput: {
    // input type
    createdAt?: NexusGenEnums['OrderByArg'] | null // OrderByArg
    position?: NexusGenEnums['OrderByArg'] | null // OrderByArg
  }
  CollectionItemsWhereInput: {
    // input type
    isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
  }
  CollectionScalarWhereInput: {
    // input type
    AND?: NexusGenInputs['CollectionScalarWhereInput'][] | null // [CollectionScalarWhereInput!]
    NOT?: NexusGenInputs['CollectionScalarWhereInput'][] | null // [CollectionScalarWhereInput!]
    OR?: NexusGenInputs['CollectionScalarWhereInput'][] | null // [CollectionScalarWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    detail?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    id?: NexusGenInputs['StringFilter'] | null // StringFilter
    isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    items?: NexusGenInputs['ItemFilter'] | null // ItemFilter
    name?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    ownerId?: NexusGenInputs['StringFilter'] | null // StringFilter
    sectionId?: NexusGenInputs['StringFilter'] | null // StringFilter
    slug?: NexusGenInputs['StringFilter'] | null // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
  }
  CollectionUpdateInput: {
    // input type
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    detail?: string | null // String
    id?: string | null // String
    isDeleted?: boolean | null // Boolean
    items?: NexusGenInputs['ItemUpdateManyWithoutCollectionInput'] | null // ItemUpdateManyWithoutCollectionInput
    name?: string | null // String
    owner?:
      | NexusGenInputs['UserUpdateOneRequiredWithoutCollectionsInput']
      | null // UserUpdateOneRequiredWithoutCollectionsInput
    section?:
      | NexusGenInputs['SectionUpdateOneRequiredWithoutCollectionsInput']
      | null // SectionUpdateOneRequiredWithoutCollectionsInput
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  CollectionUpdateManyDataInput: {
    // input type
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    detail?: string | null // String
    id?: string | null // String
    isDeleted?: boolean | null // Boolean
    name?: string | null // String
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  CollectionUpdateManyWithWhereNestedInput: {
    // input type
    data: NexusGenInputs['CollectionUpdateManyDataInput'] // CollectionUpdateManyDataInput!
    where: NexusGenInputs['CollectionScalarWhereInput'] // CollectionScalarWhereInput!
  }
  CollectionUpdateManyWithoutOwnerInput: {
    // input type
    connect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
    create?: NexusGenInputs['CollectionCreateWithoutOwnerInput'][] | null // [CollectionCreateWithoutOwnerInput!]
    delete?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
    deleteMany?: NexusGenInputs['CollectionScalarWhereInput'][] | null // [CollectionScalarWhereInput!]
    disconnect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
    set?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
    update?:
      | NexusGenInputs['CollectionUpdateWithWhereUniqueWithoutOwnerInput'][]
      | null // [CollectionUpdateWithWhereUniqueWithoutOwnerInput!]
    updateMany?:
      | NexusGenInputs['CollectionUpdateManyWithWhereNestedInput'][]
      | null // [CollectionUpdateManyWithWhereNestedInput!]
    upsert?:
      | NexusGenInputs['CollectionUpsertWithWhereUniqueWithoutOwnerInput'][]
      | null // [CollectionUpsertWithWhereUniqueWithoutOwnerInput!]
  }
  CollectionUpdateManyWithoutSectionInput: {
    // input type
    connect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
    create?: NexusGenInputs['CollectionCreateWithoutSectionInput'][] | null // [CollectionCreateWithoutSectionInput!]
    delete?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
    deleteMany?: NexusGenInputs['CollectionScalarWhereInput'][] | null // [CollectionScalarWhereInput!]
    disconnect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
    set?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
    update?:
      | NexusGenInputs['CollectionUpdateWithWhereUniqueWithoutSectionInput'][]
      | null // [CollectionUpdateWithWhereUniqueWithoutSectionInput!]
    updateMany?:
      | NexusGenInputs['CollectionUpdateManyWithWhereNestedInput'][]
      | null // [CollectionUpdateManyWithWhereNestedInput!]
    upsert?:
      | NexusGenInputs['CollectionUpsertWithWhereUniqueWithoutSectionInput'][]
      | null // [CollectionUpsertWithWhereUniqueWithoutSectionInput!]
  }
  CollectionUpdateOneWithoutItemsInput: {
    // input type
    connect?: NexusGenInputs['CollectionWhereUniqueInput'] | null // CollectionWhereUniqueInput
    create?: NexusGenInputs['CollectionCreateWithoutItemsInput'] | null // CollectionCreateWithoutItemsInput
    delete?: boolean | null // Boolean
    disconnect?: boolean | null // Boolean
    update?: NexusGenInputs['CollectionUpdateWithoutItemsDataInput'] | null // CollectionUpdateWithoutItemsDataInput
    upsert?: NexusGenInputs['CollectionUpsertWithoutItemsInput'] | null // CollectionUpsertWithoutItemsInput
  }
  CollectionUpdateWithWhereUniqueWithoutOwnerInput: {
    // input type
    data: NexusGenInputs['CollectionUpdateWithoutOwnerDataInput'] // CollectionUpdateWithoutOwnerDataInput!
    where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
  }
  CollectionUpdateWithWhereUniqueWithoutSectionInput: {
    // input type
    data: NexusGenInputs['CollectionUpdateWithoutSectionDataInput'] // CollectionUpdateWithoutSectionDataInput!
    where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
  }
  CollectionUpdateWithoutItemsDataInput: {
    // input type
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    detail?: string | null // String
    id?: string | null // String
    isDeleted?: boolean | null // Boolean
    name?: string | null // String
    owner?:
      | NexusGenInputs['UserUpdateOneRequiredWithoutCollectionsInput']
      | null // UserUpdateOneRequiredWithoutCollectionsInput
    section?:
      | NexusGenInputs['SectionUpdateOneRequiredWithoutCollectionsInput']
      | null // SectionUpdateOneRequiredWithoutCollectionsInput
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  CollectionUpdateWithoutOwnerDataInput: {
    // input type
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    detail?: string | null // String
    id?: string | null // String
    isDeleted?: boolean | null // Boolean
    items?: NexusGenInputs['ItemUpdateManyWithoutCollectionInput'] | null // ItemUpdateManyWithoutCollectionInput
    name?: string | null // String
    section?:
      | NexusGenInputs['SectionUpdateOneRequiredWithoutCollectionsInput']
      | null // SectionUpdateOneRequiredWithoutCollectionsInput
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  CollectionUpdateWithoutSectionDataInput: {
    // input type
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    detail?: string | null // String
    id?: string | null // String
    isDeleted?: boolean | null // Boolean
    items?: NexusGenInputs['ItemUpdateManyWithoutCollectionInput'] | null // ItemUpdateManyWithoutCollectionInput
    name?: string | null // String
    owner?:
      | NexusGenInputs['UserUpdateOneRequiredWithoutCollectionsInput']
      | null // UserUpdateOneRequiredWithoutCollectionsInput
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  CollectionUpsertWithWhereUniqueWithoutOwnerInput: {
    // input type
    create: NexusGenInputs['CollectionCreateWithoutOwnerInput'] // CollectionCreateWithoutOwnerInput!
    update: NexusGenInputs['CollectionUpdateWithoutOwnerDataInput'] // CollectionUpdateWithoutOwnerDataInput!
    where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
  }
  CollectionUpsertWithWhereUniqueWithoutSectionInput: {
    // input type
    create: NexusGenInputs['CollectionCreateWithoutSectionInput'] // CollectionCreateWithoutSectionInput!
    update: NexusGenInputs['CollectionUpdateWithoutSectionDataInput'] // CollectionUpdateWithoutSectionDataInput!
    where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
  }
  CollectionUpsertWithoutItemsInput: {
    // input type
    create: NexusGenInputs['CollectionCreateWithoutItemsInput'] // CollectionCreateWithoutItemsInput!
    update: NexusGenInputs['CollectionUpdateWithoutItemsDataInput'] // CollectionUpdateWithoutItemsDataInput!
  }
  CollectionWhereInput: {
    // input type
    AND?: NexusGenInputs['CollectionWhereInput'][] | null // [CollectionWhereInput!]
    NOT?: NexusGenInputs['CollectionWhereInput'][] | null // [CollectionWhereInput!]
    OR?: NexusGenInputs['CollectionWhereInput'][] | null // [CollectionWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    detail?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    id?: NexusGenInputs['StringFilter'] | null // StringFilter
    isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    items?: NexusGenInputs['ItemFilter'] | null // ItemFilter
    name?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    owner?: NexusGenInputs['UserWhereInput'] | null // UserWhereInput
    ownerId?: NexusGenInputs['StringFilter'] | null // StringFilter
    section?: NexusGenInputs['SectionWhereInput'] | null // SectionWhereInput
    sectionId?: NexusGenInputs['StringFilter'] | null // StringFilter
    slug?: NexusGenInputs['StringFilter'] | null // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
  }
  CollectionWhereUniqueInput: {
    // input type
    id?: string | null // String
    slug?: string | null // String
  }
  DateTimeFilter: {
    // input type
    equals?: NexusGenScalars['DateTime'] | null // DateTime
    gt?: NexusGenScalars['DateTime'] | null // DateTime
    gte?: NexusGenScalars['DateTime'] | null // DateTime
    in?: NexusGenScalars['DateTime'][] | null // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null // DateTime
    lte?: NexusGenScalars['DateTime'] | null // DateTime
    not?: NexusGenScalars['DateTime'] | null // DateTime
    notIn?: NexusGenScalars['DateTime'][] | null // [DateTime!]
  }
  IntFilter: {
    // input type
    equals?: number | null // Int
    gt?: number | null // Int
    gte?: number | null // Int
    in?: number[] | null // [Int!]
    lt?: number | null // Int
    lte?: number | null // Int
    not?: number | null // Int
    notIn?: number[] | null // [Int!]
  }
  ItemCreateManyWithoutCollectionInput: {
    // input type
    connect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
    create?: NexusGenInputs['ItemCreateWithoutCollectionInput'][] | null // [ItemCreateWithoutCollectionInput!]
  }
  ItemCreateManyWithoutInboxOwnerInput: {
    // input type
    connect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
    create?: NexusGenInputs['ItemCreateWithoutInboxOwnerInput'][] | null // [ItemCreateWithoutInboxOwnerInput!]
  }
  ItemCreateWithoutCollectionInput: {
    // input type
    author?: string | null // String
    comment?: string | null // String
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    description?: string | null // String
    id?: string | null // String
    imageUrl?: string | null // String
    inboxOwner?: NexusGenInputs['UserCreateOneWithoutInboxedItemsInput'] | null // UserCreateOneWithoutInboxedItemsInput
    isDeleted?: boolean | null // Boolean
    meta?: string | null // String
    position?: number | null // Int
    productUrl?: string | null // String
    provider?: string | null // String
    title: string // String!
    type: NexusGenEnums['ItemType'] // ItemType!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  ItemCreateWithoutInboxOwnerInput: {
    // input type
    author?: string | null // String
    collection?: NexusGenInputs['CollectionCreateOneWithoutItemsInput'] | null // CollectionCreateOneWithoutItemsInput
    comment?: string | null // String
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    description?: string | null // String
    id?: string | null // String
    imageUrl?: string | null // String
    isDeleted?: boolean | null // Boolean
    meta?: string | null // String
    position?: number | null // Int
    productUrl?: string | null // String
    provider?: string | null // String
    title: string // String!
    type: NexusGenEnums['ItemType'] // ItemType!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  ItemFilter: {
    // input type
    every?: NexusGenInputs['ItemWhereInput'] | null // ItemWhereInput
    none?: NexusGenInputs['ItemWhereInput'] | null // ItemWhereInput
    some?: NexusGenInputs['ItemWhereInput'] | null // ItemWhereInput
  }
  ItemScalarWhereInput: {
    // input type
    AND?: NexusGenInputs['ItemScalarWhereInput'][] | null // [ItemScalarWhereInput!]
    NOT?: NexusGenInputs['ItemScalarWhereInput'][] | null // [ItemScalarWhereInput!]
    OR?: NexusGenInputs['ItemScalarWhereInput'][] | null // [ItemScalarWhereInput!]
    author?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    collectionId?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    comment?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    description?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    id?: NexusGenInputs['StringFilter'] | null // StringFilter
    imageUrl?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    inboxOwnerId?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    meta?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    position?: NexusGenInputs['IntFilter'] | null // IntFilter
    productUrl?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    provider?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    title?: NexusGenInputs['StringFilter'] | null // StringFilter
    type?: NexusGenEnums['ItemType'] | null // ItemType
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
  }
  ItemUpdateInput: {
    // input type
    author?: string | null // String
    collection?: NexusGenInputs['CollectionUpdateOneWithoutItemsInput'] | null // CollectionUpdateOneWithoutItemsInput
    comment?: string | null // String
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    description?: string | null // String
    id?: string | null // String
    imageUrl?: string | null // String
    inboxOwner?: NexusGenInputs['UserUpdateOneWithoutInboxedItemsInput'] | null // UserUpdateOneWithoutInboxedItemsInput
    isDeleted?: boolean | null // Boolean
    meta?: string | null // String
    position?: number | null // Int
    productUrl?: string | null // String
    provider?: string | null // String
    title?: string | null // String
    type?: NexusGenEnums['ItemType'] | null // ItemType
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  ItemUpdateManyDataInput: {
    // input type
    author?: string | null // String
    comment?: string | null // String
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    description?: string | null // String
    id?: string | null // String
    imageUrl?: string | null // String
    isDeleted?: boolean | null // Boolean
    meta?: string | null // String
    position?: number | null // Int
    productUrl?: string | null // String
    provider?: string | null // String
    title?: string | null // String
    type?: NexusGenEnums['ItemType'] | null // ItemType
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  ItemUpdateManyWithWhereNestedInput: {
    // input type
    data: NexusGenInputs['ItemUpdateManyDataInput'] // ItemUpdateManyDataInput!
    where: NexusGenInputs['ItemScalarWhereInput'] // ItemScalarWhereInput!
  }
  ItemUpdateManyWithoutCollectionInput: {
    // input type
    connect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
    create?: NexusGenInputs['ItemCreateWithoutCollectionInput'][] | null // [ItemCreateWithoutCollectionInput!]
    delete?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
    deleteMany?: NexusGenInputs['ItemScalarWhereInput'][] | null // [ItemScalarWhereInput!]
    disconnect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
    set?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
    update?:
      | NexusGenInputs['ItemUpdateWithWhereUniqueWithoutCollectionInput'][]
      | null // [ItemUpdateWithWhereUniqueWithoutCollectionInput!]
    updateMany?: NexusGenInputs['ItemUpdateManyWithWhereNestedInput'][] | null // [ItemUpdateManyWithWhereNestedInput!]
    upsert?:
      | NexusGenInputs['ItemUpsertWithWhereUniqueWithoutCollectionInput'][]
      | null // [ItemUpsertWithWhereUniqueWithoutCollectionInput!]
  }
  ItemUpdateManyWithoutInboxOwnerInput: {
    // input type
    connect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
    create?: NexusGenInputs['ItemCreateWithoutInboxOwnerInput'][] | null // [ItemCreateWithoutInboxOwnerInput!]
    delete?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
    deleteMany?: NexusGenInputs['ItemScalarWhereInput'][] | null // [ItemScalarWhereInput!]
    disconnect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
    set?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
    update?:
      | NexusGenInputs['ItemUpdateWithWhereUniqueWithoutInboxOwnerInput'][]
      | null // [ItemUpdateWithWhereUniqueWithoutInboxOwnerInput!]
    updateMany?: NexusGenInputs['ItemUpdateManyWithWhereNestedInput'][] | null // [ItemUpdateManyWithWhereNestedInput!]
    upsert?:
      | NexusGenInputs['ItemUpsertWithWhereUniqueWithoutInboxOwnerInput'][]
      | null // [ItemUpsertWithWhereUniqueWithoutInboxOwnerInput!]
  }
  ItemUpdateWithWhereUniqueWithoutCollectionInput: {
    // input type
    data: NexusGenInputs['ItemUpdateWithoutCollectionDataInput'] // ItemUpdateWithoutCollectionDataInput!
    where: NexusGenInputs['ItemWhereUniqueInput'] // ItemWhereUniqueInput!
  }
  ItemUpdateWithWhereUniqueWithoutInboxOwnerInput: {
    // input type
    data: NexusGenInputs['ItemUpdateWithoutInboxOwnerDataInput'] // ItemUpdateWithoutInboxOwnerDataInput!
    where: NexusGenInputs['ItemWhereUniqueInput'] // ItemWhereUniqueInput!
  }
  ItemUpdateWithoutCollectionDataInput: {
    // input type
    author?: string | null // String
    comment?: string | null // String
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    description?: string | null // String
    id?: string | null // String
    imageUrl?: string | null // String
    inboxOwner?: NexusGenInputs['UserUpdateOneWithoutInboxedItemsInput'] | null // UserUpdateOneWithoutInboxedItemsInput
    isDeleted?: boolean | null // Boolean
    meta?: string | null // String
    position?: number | null // Int
    productUrl?: string | null // String
    provider?: string | null // String
    title?: string | null // String
    type?: NexusGenEnums['ItemType'] | null // ItemType
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  ItemUpdateWithoutInboxOwnerDataInput: {
    // input type
    author?: string | null // String
    collection?: NexusGenInputs['CollectionUpdateOneWithoutItemsInput'] | null // CollectionUpdateOneWithoutItemsInput
    comment?: string | null // String
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    description?: string | null // String
    id?: string | null // String
    imageUrl?: string | null // String
    isDeleted?: boolean | null // Boolean
    meta?: string | null // String
    position?: number | null // Int
    productUrl?: string | null // String
    provider?: string | null // String
    title?: string | null // String
    type?: NexusGenEnums['ItemType'] | null // ItemType
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  ItemUpsertWithWhereUniqueWithoutCollectionInput: {
    // input type
    create: NexusGenInputs['ItemCreateWithoutCollectionInput'] // ItemCreateWithoutCollectionInput!
    update: NexusGenInputs['ItemUpdateWithoutCollectionDataInput'] // ItemUpdateWithoutCollectionDataInput!
    where: NexusGenInputs['ItemWhereUniqueInput'] // ItemWhereUniqueInput!
  }
  ItemUpsertWithWhereUniqueWithoutInboxOwnerInput: {
    // input type
    create: NexusGenInputs['ItemCreateWithoutInboxOwnerInput'] // ItemCreateWithoutInboxOwnerInput!
    update: NexusGenInputs['ItemUpdateWithoutInboxOwnerDataInput'] // ItemUpdateWithoutInboxOwnerDataInput!
    where: NexusGenInputs['ItemWhereUniqueInput'] // ItemWhereUniqueInput!
  }
  ItemWhereInput: {
    // input type
    AND?: NexusGenInputs['ItemWhereInput'][] | null // [ItemWhereInput!]
    NOT?: NexusGenInputs['ItemWhereInput'][] | null // [ItemWhereInput!]
    OR?: NexusGenInputs['ItemWhereInput'][] | null // [ItemWhereInput!]
    author?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    collection?: NexusGenInputs['CollectionWhereInput'] | null // CollectionWhereInput
    collectionId?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    comment?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    description?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    id?: NexusGenInputs['StringFilter'] | null // StringFilter
    imageUrl?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    inboxOwner?: NexusGenInputs['UserWhereInput'] | null // UserWhereInput
    inboxOwnerId?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    meta?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    position?: NexusGenInputs['IntFilter'] | null // IntFilter
    productUrl?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    provider?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    title?: NexusGenInputs['StringFilter'] | null // StringFilter
    type?: NexusGenEnums['ItemType'] | null // ItemType
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
  }
  ItemWhereUniqueInput: {
    // input type
    id?: string | null // String
  }
  NullableStringFilter: {
    // input type
    contains?: string | null // String
    endsWith?: string | null // String
    equals?: string | null // String
    gt?: string | null // String
    gte?: string | null // String
    in?: string[] | null // [String!]
    lt?: string | null // String
    lte?: string | null // String
    not?: string | null // String
    notIn?: string[] | null // [String!]
    startsWith?: string | null // String
  }
  QueryCollectionsOrderByInput: {
    // input type
    createdAt?: NexusGenEnums['OrderByArg'] | null // OrderByArg
  }
  QueryCollectionsWhereInput: {
    // input type
    isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    owner?: NexusGenInputs['UserWhereInput'] | null // UserWhereInput
    section?: NexusGenInputs['SectionWhereInput'] | null // SectionWhereInput
  }
  QueryItemsOrderByInput: {
    // input type
    position?: NexusGenEnums['OrderByArg'] | null // OrderByArg
  }
  QueryItemsWhereInput: {
    // input type
    collection?: NexusGenInputs['CollectionWhereInput'] | null // CollectionWhereInput
    isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
  }
  QuerySectionsOrderByInput: {
    // input type
    createdAt?: NexusGenEnums['OrderByArg'] | null // OrderByArg
  }
  QuerySectionsWhereInput: {
    // input type
    index?: NexusGenInputs['IntFilter'] | null // IntFilter
    isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    owner?: NexusGenInputs['UserWhereInput'] | null // UserWhereInput
  }
  SectionCollectionsOrderByInput: {
    // input type
    createdAt?: NexusGenEnums['OrderByArg'] | null // OrderByArg
    updatedAt?: NexusGenEnums['OrderByArg'] | null // OrderByArg
  }
  SectionCollectionsWhereInput: {
    // input type
    isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
  }
  SectionCreateManyWithoutOwnerInput: {
    // input type
    connect?: NexusGenInputs['SectionWhereUniqueInput'][] | null // [SectionWhereUniqueInput!]
    create?: NexusGenInputs['SectionCreateWithoutOwnerInput'][] | null // [SectionCreateWithoutOwnerInput!]
  }
  SectionCreateOneWithoutCollectionsInput: {
    // input type
    connect?: NexusGenInputs['SectionWhereUniqueInput'] | null // SectionWhereUniqueInput
    create?: NexusGenInputs['SectionCreateWithoutCollectionsInput'] | null // SectionCreateWithoutCollectionsInput
  }
  SectionCreateWithoutCollectionsInput: {
    // input type
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    id?: string | null // String
    index?: number | null // Int
    isDeleted?: boolean | null // Boolean
    isExpanded?: boolean | null // Boolean
    name?: string | null // String
    owner: NexusGenInputs['UserCreateOneWithoutSectionsInput'] // UserCreateOneWithoutSectionsInput!
    slug: string // String!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  SectionCreateWithoutOwnerInput: {
    // input type
    collections?:
      | NexusGenInputs['CollectionCreateManyWithoutSectionInput']
      | null // CollectionCreateManyWithoutSectionInput
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    id?: string | null // String
    index?: number | null // Int
    isDeleted?: boolean | null // Boolean
    isExpanded?: boolean | null // Boolean
    name?: string | null // String
    slug: string // String!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  SectionFilter: {
    // input type
    every?: NexusGenInputs['SectionWhereInput'] | null // SectionWhereInput
    none?: NexusGenInputs['SectionWhereInput'] | null // SectionWhereInput
    some?: NexusGenInputs['SectionWhereInput'] | null // SectionWhereInput
  }
  SectionScalarWhereInput: {
    // input type
    AND?: NexusGenInputs['SectionScalarWhereInput'][] | null // [SectionScalarWhereInput!]
    NOT?: NexusGenInputs['SectionScalarWhereInput'][] | null // [SectionScalarWhereInput!]
    OR?: NexusGenInputs['SectionScalarWhereInput'][] | null // [SectionScalarWhereInput!]
    collections?: NexusGenInputs['CollectionFilter'] | null // CollectionFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null // StringFilter
    index?: NexusGenInputs['IntFilter'] | null // IntFilter
    isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    isExpanded?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    name?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    ownerId?: NexusGenInputs['StringFilter'] | null // StringFilter
    slug?: NexusGenInputs['StringFilter'] | null // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
  }
  SectionUpdateInput: {
    // input type
    collections?:
      | NexusGenInputs['CollectionUpdateManyWithoutSectionInput']
      | null // CollectionUpdateManyWithoutSectionInput
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    id?: string | null // String
    index?: number | null // Int
    isDeleted?: boolean | null // Boolean
    isExpanded?: boolean | null // Boolean
    name?: string | null // String
    owner?: NexusGenInputs['UserUpdateOneRequiredWithoutSectionsInput'] | null // UserUpdateOneRequiredWithoutSectionsInput
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  SectionUpdateManyDataInput: {
    // input type
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    id?: string | null // String
    index?: number | null // Int
    isDeleted?: boolean | null // Boolean
    isExpanded?: boolean | null // Boolean
    name?: string | null // String
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  SectionUpdateManyWithWhereNestedInput: {
    // input type
    data: NexusGenInputs['SectionUpdateManyDataInput'] // SectionUpdateManyDataInput!
    where: NexusGenInputs['SectionScalarWhereInput'] // SectionScalarWhereInput!
  }
  SectionUpdateManyWithoutOwnerInput: {
    // input type
    connect?: NexusGenInputs['SectionWhereUniqueInput'][] | null // [SectionWhereUniqueInput!]
    create?: NexusGenInputs['SectionCreateWithoutOwnerInput'][] | null // [SectionCreateWithoutOwnerInput!]
    delete?: NexusGenInputs['SectionWhereUniqueInput'][] | null // [SectionWhereUniqueInput!]
    deleteMany?: NexusGenInputs['SectionScalarWhereInput'][] | null // [SectionScalarWhereInput!]
    disconnect?: NexusGenInputs['SectionWhereUniqueInput'][] | null // [SectionWhereUniqueInput!]
    set?: NexusGenInputs['SectionWhereUniqueInput'][] | null // [SectionWhereUniqueInput!]
    update?:
      | NexusGenInputs['SectionUpdateWithWhereUniqueWithoutOwnerInput'][]
      | null // [SectionUpdateWithWhereUniqueWithoutOwnerInput!]
    updateMany?:
      | NexusGenInputs['SectionUpdateManyWithWhereNestedInput'][]
      | null // [SectionUpdateManyWithWhereNestedInput!]
    upsert?:
      | NexusGenInputs['SectionUpsertWithWhereUniqueWithoutOwnerInput'][]
      | null // [SectionUpsertWithWhereUniqueWithoutOwnerInput!]
  }
  SectionUpdateOneRequiredWithoutCollectionsInput: {
    // input type
    connect?: NexusGenInputs['SectionWhereUniqueInput'] | null // SectionWhereUniqueInput
    create?: NexusGenInputs['SectionCreateWithoutCollectionsInput'] | null // SectionCreateWithoutCollectionsInput
    update?: NexusGenInputs['SectionUpdateWithoutCollectionsDataInput'] | null // SectionUpdateWithoutCollectionsDataInput
    upsert?: NexusGenInputs['SectionUpsertWithoutCollectionsInput'] | null // SectionUpsertWithoutCollectionsInput
  }
  SectionUpdateWithWhereUniqueWithoutOwnerInput: {
    // input type
    data: NexusGenInputs['SectionUpdateWithoutOwnerDataInput'] // SectionUpdateWithoutOwnerDataInput!
    where: NexusGenInputs['SectionWhereUniqueInput'] // SectionWhereUniqueInput!
  }
  SectionUpdateWithoutCollectionsDataInput: {
    // input type
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    id?: string | null // String
    index?: number | null // Int
    isDeleted?: boolean | null // Boolean
    isExpanded?: boolean | null // Boolean
    name?: string | null // String
    owner?: NexusGenInputs['UserUpdateOneRequiredWithoutSectionsInput'] | null // UserUpdateOneRequiredWithoutSectionsInput
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  SectionUpdateWithoutOwnerDataInput: {
    // input type
    collections?:
      | NexusGenInputs['CollectionUpdateManyWithoutSectionInput']
      | null // CollectionUpdateManyWithoutSectionInput
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    id?: string | null // String
    index?: number | null // Int
    isDeleted?: boolean | null // Boolean
    isExpanded?: boolean | null // Boolean
    name?: string | null // String
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  SectionUpsertWithWhereUniqueWithoutOwnerInput: {
    // input type
    create: NexusGenInputs['SectionCreateWithoutOwnerInput'] // SectionCreateWithoutOwnerInput!
    update: NexusGenInputs['SectionUpdateWithoutOwnerDataInput'] // SectionUpdateWithoutOwnerDataInput!
    where: NexusGenInputs['SectionWhereUniqueInput'] // SectionWhereUniqueInput!
  }
  SectionUpsertWithoutCollectionsInput: {
    // input type
    create: NexusGenInputs['SectionCreateWithoutCollectionsInput'] // SectionCreateWithoutCollectionsInput!
    update: NexusGenInputs['SectionUpdateWithoutCollectionsDataInput'] // SectionUpdateWithoutCollectionsDataInput!
  }
  SectionWhereInput: {
    // input type
    AND?: NexusGenInputs['SectionWhereInput'][] | null // [SectionWhereInput!]
    NOT?: NexusGenInputs['SectionWhereInput'][] | null // [SectionWhereInput!]
    OR?: NexusGenInputs['SectionWhereInput'][] | null // [SectionWhereInput!]
    collections?: NexusGenInputs['CollectionFilter'] | null // CollectionFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null // StringFilter
    index?: NexusGenInputs['IntFilter'] | null // IntFilter
    isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    isExpanded?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    name?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    owner?: NexusGenInputs['UserWhereInput'] | null // UserWhereInput
    ownerId?: NexusGenInputs['StringFilter'] | null // StringFilter
    slug?: NexusGenInputs['StringFilter'] | null // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
  }
  SectionWhereUniqueInput: {
    // input type
    id?: string | null // String
  }
  StringFilter: {
    // input type
    contains?: string | null // String
    endsWith?: string | null // String
    equals?: string | null // String
    gt?: string | null // String
    gte?: string | null // String
    in?: string[] | null // [String!]
    lt?: string | null // String
    lte?: string | null // String
    not?: string | null // String
    notIn?: string[] | null // [String!]
    startsWith?: string | null // String
  }
  UserCreateInput: {
    // input type
    authUserId?: string | null // String
    biography?: string | null // String
    collections?: NexusGenInputs['CollectionCreateManyWithoutOwnerInput'] | null // CollectionCreateManyWithoutOwnerInput
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    firstname: string // String!
    github?: string | null // String
    id?: string | null // String
    inboxedItems?: NexusGenInputs['ItemCreateManyWithoutInboxOwnerInput'] | null // ItemCreateManyWithoutInboxOwnerInput
    label?: string | null // String
    linkedin?: string | null // String
    mail?: string | null // String
    pictureUrl: string // String!
    sections?: NexusGenInputs['SectionCreateManyWithoutOwnerInput'] | null // SectionCreateManyWithoutOwnerInput
    slug: string // String!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
    website?: string | null // String
    youtube?: string | null // String
  }
  UserCreateOneWithoutCollectionsInput: {
    // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null // UserWhereUniqueInput
    create?: NexusGenInputs['UserCreateWithoutCollectionsInput'] | null // UserCreateWithoutCollectionsInput
  }
  UserCreateOneWithoutInboxedItemsInput: {
    // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null // UserWhereUniqueInput
    create?: NexusGenInputs['UserCreateWithoutInboxedItemsInput'] | null // UserCreateWithoutInboxedItemsInput
  }
  UserCreateOneWithoutSectionsInput: {
    // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null // UserWhereUniqueInput
    create?: NexusGenInputs['UserCreateWithoutSectionsInput'] | null // UserCreateWithoutSectionsInput
  }
  UserCreateWithoutCollectionsInput: {
    // input type
    authUserId?: string | null // String
    biography?: string | null // String
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    firstname: string // String!
    github?: string | null // String
    id?: string | null // String
    inboxedItems?: NexusGenInputs['ItemCreateManyWithoutInboxOwnerInput'] | null // ItemCreateManyWithoutInboxOwnerInput
    label?: string | null // String
    linkedin?: string | null // String
    mail?: string | null // String
    pictureUrl: string // String!
    sections?: NexusGenInputs['SectionCreateManyWithoutOwnerInput'] | null // SectionCreateManyWithoutOwnerInput
    slug: string // String!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
    website?: string | null // String
    youtube?: string | null // String
  }
  UserCreateWithoutInboxedItemsInput: {
    // input type
    authUserId?: string | null // String
    biography?: string | null // String
    collections?: NexusGenInputs['CollectionCreateManyWithoutOwnerInput'] | null // CollectionCreateManyWithoutOwnerInput
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    firstname: string // String!
    github?: string | null // String
    id?: string | null // String
    label?: string | null // String
    linkedin?: string | null // String
    mail?: string | null // String
    pictureUrl: string // String!
    sections?: NexusGenInputs['SectionCreateManyWithoutOwnerInput'] | null // SectionCreateManyWithoutOwnerInput
    slug: string // String!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
    website?: string | null // String
    youtube?: string | null // String
  }
  UserCreateWithoutSectionsInput: {
    // input type
    authUserId?: string | null // String
    biography?: string | null // String
    collections?: NexusGenInputs['CollectionCreateManyWithoutOwnerInput'] | null // CollectionCreateManyWithoutOwnerInput
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    firstname: string // String!
    github?: string | null // String
    id?: string | null // String
    inboxedItems?: NexusGenInputs['ItemCreateManyWithoutInboxOwnerInput'] | null // ItemCreateManyWithoutInboxOwnerInput
    label?: string | null // String
    linkedin?: string | null // String
    mail?: string | null // String
    pictureUrl: string // String!
    slug: string // String!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
    website?: string | null // String
    youtube?: string | null // String
  }
  UserUpdateInput: {
    // input type
    authUserId?: string | null // String
    biography?: string | null // String
    collections?: NexusGenInputs['CollectionUpdateManyWithoutOwnerInput'] | null // CollectionUpdateManyWithoutOwnerInput
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    firstname?: string | null // String
    github?: string | null // String
    id?: string | null // String
    inboxedItems?: NexusGenInputs['ItemUpdateManyWithoutInboxOwnerInput'] | null // ItemUpdateManyWithoutInboxOwnerInput
    label?: string | null // String
    linkedin?: string | null // String
    mail?: string | null // String
    pictureUrl?: string | null // String
    sections?: NexusGenInputs['SectionUpdateManyWithoutOwnerInput'] | null // SectionUpdateManyWithoutOwnerInput
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
    website?: string | null // String
    youtube?: string | null // String
  }
  UserUpdateOneRequiredWithoutCollectionsInput: {
    // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null // UserWhereUniqueInput
    create?: NexusGenInputs['UserCreateWithoutCollectionsInput'] | null // UserCreateWithoutCollectionsInput
    update?: NexusGenInputs['UserUpdateWithoutCollectionsDataInput'] | null // UserUpdateWithoutCollectionsDataInput
    upsert?: NexusGenInputs['UserUpsertWithoutCollectionsInput'] | null // UserUpsertWithoutCollectionsInput
  }
  UserUpdateOneRequiredWithoutSectionsInput: {
    // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null // UserWhereUniqueInput
    create?: NexusGenInputs['UserCreateWithoutSectionsInput'] | null // UserCreateWithoutSectionsInput
    update?: NexusGenInputs['UserUpdateWithoutSectionsDataInput'] | null // UserUpdateWithoutSectionsDataInput
    upsert?: NexusGenInputs['UserUpsertWithoutSectionsInput'] | null // UserUpsertWithoutSectionsInput
  }
  UserUpdateOneWithoutInboxedItemsInput: {
    // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null // UserWhereUniqueInput
    create?: NexusGenInputs['UserCreateWithoutInboxedItemsInput'] | null // UserCreateWithoutInboxedItemsInput
    delete?: boolean | null // Boolean
    disconnect?: boolean | null // Boolean
    update?: NexusGenInputs['UserUpdateWithoutInboxedItemsDataInput'] | null // UserUpdateWithoutInboxedItemsDataInput
    upsert?: NexusGenInputs['UserUpsertWithoutInboxedItemsInput'] | null // UserUpsertWithoutInboxedItemsInput
  }
  UserUpdateWithoutCollectionsDataInput: {
    // input type
    authUserId?: string | null // String
    biography?: string | null // String
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    firstname?: string | null // String
    github?: string | null // String
    id?: string | null // String
    inboxedItems?: NexusGenInputs['ItemUpdateManyWithoutInboxOwnerInput'] | null // ItemUpdateManyWithoutInboxOwnerInput
    label?: string | null // String
    linkedin?: string | null // String
    mail?: string | null // String
    pictureUrl?: string | null // String
    sections?: NexusGenInputs['SectionUpdateManyWithoutOwnerInput'] | null // SectionUpdateManyWithoutOwnerInput
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
    website?: string | null // String
    youtube?: string | null // String
  }
  UserUpdateWithoutInboxedItemsDataInput: {
    // input type
    authUserId?: string | null // String
    biography?: string | null // String
    collections?: NexusGenInputs['CollectionUpdateManyWithoutOwnerInput'] | null // CollectionUpdateManyWithoutOwnerInput
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    firstname?: string | null // String
    github?: string | null // String
    id?: string | null // String
    label?: string | null // String
    linkedin?: string | null // String
    mail?: string | null // String
    pictureUrl?: string | null // String
    sections?: NexusGenInputs['SectionUpdateManyWithoutOwnerInput'] | null // SectionUpdateManyWithoutOwnerInput
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
    website?: string | null // String
    youtube?: string | null // String
  }
  UserUpdateWithoutSectionsDataInput: {
    // input type
    authUserId?: string | null // String
    biography?: string | null // String
    collections?: NexusGenInputs['CollectionUpdateManyWithoutOwnerInput'] | null // CollectionUpdateManyWithoutOwnerInput
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    firstname?: string | null // String
    github?: string | null // String
    id?: string | null // String
    inboxedItems?: NexusGenInputs['ItemUpdateManyWithoutInboxOwnerInput'] | null // ItemUpdateManyWithoutInboxOwnerInput
    label?: string | null // String
    linkedin?: string | null // String
    mail?: string | null // String
    pictureUrl?: string | null // String
    slug?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
    website?: string | null // String
    youtube?: string | null // String
  }
  UserUpsertWithoutCollectionsInput: {
    // input type
    create: NexusGenInputs['UserCreateWithoutCollectionsInput'] // UserCreateWithoutCollectionsInput!
    update: NexusGenInputs['UserUpdateWithoutCollectionsDataInput'] // UserUpdateWithoutCollectionsDataInput!
  }
  UserUpsertWithoutInboxedItemsInput: {
    // input type
    create: NexusGenInputs['UserCreateWithoutInboxedItemsInput'] // UserCreateWithoutInboxedItemsInput!
    update: NexusGenInputs['UserUpdateWithoutInboxedItemsDataInput'] // UserUpdateWithoutInboxedItemsDataInput!
  }
  UserUpsertWithoutSectionsInput: {
    // input type
    create: NexusGenInputs['UserCreateWithoutSectionsInput'] // UserCreateWithoutSectionsInput!
    update: NexusGenInputs['UserUpdateWithoutSectionsDataInput'] // UserUpdateWithoutSectionsDataInput!
  }
  UserWhereInput: {
    // input type
    AND?: NexusGenInputs['UserWhereInput'][] | null // [UserWhereInput!]
    NOT?: NexusGenInputs['UserWhereInput'][] | null // [UserWhereInput!]
    OR?: NexusGenInputs['UserWhereInput'][] | null // [UserWhereInput!]
    authUserId?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    biography?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    collections?: NexusGenInputs['CollectionFilter'] | null // CollectionFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    firstname?: NexusGenInputs['StringFilter'] | null // StringFilter
    github?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    id?: NexusGenInputs['StringFilter'] | null // StringFilter
    inboxedItems?: NexusGenInputs['ItemFilter'] | null // ItemFilter
    label?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    linkedin?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    mail?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    pictureUrl?: NexusGenInputs['StringFilter'] | null // StringFilter
    sections?: NexusGenInputs['SectionFilter'] | null // SectionFilter
    slug?: NexusGenInputs['StringFilter'] | null // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    website?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    youtube?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
  }
  UserWhereUniqueInput: {
    // input type
    authUserId?: string | null // String
    id?: string | null // String
    slug?: string | null // String
  }
}

export interface NexusGenEnums {
  ItemType:
    | 'album'
    | 'article'
    | 'book'
    | 'movie'
    | 'people'
    | 'podcast'
    | 'repository'
    | 'video'
    | 'website'
  OrderByArg: 'asc' | 'desc'
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Collection: {
    // root type
    createdAt: NexusGenScalars['DateTime'] // DateTime!
    detail?: string | null // String
    id: string // String!
    isDeleted: boolean // Boolean!
    items: NexusGenRootTypes['Item'][] // [Item!]!
    name?: string | null // String
    owner: NexusGenRootTypes['User'] // User!
    section: NexusGenRootTypes['Section'] // Section!
    slug: string // String!
    updatedAt: NexusGenScalars['DateTime'] // DateTime!
  }
  Inbox: {}
  Item: {
    // root type
    author?: string | null // String
    comment?: string | null // String
    createdAt: NexusGenScalars['DateTime'] // DateTime!
    description?: string | null // String
    id: string // String!
    imageUrl?: string | null // String
    isDeleted: boolean // Boolean!
    meta?: string | null // String
    position: number // Int!
    productUrl?: string | null // String
    provider?: string | null // String
    title: string // String!
    type: NexusGenEnums['ItemType'] // ItemType!
  }
  Mutation: {}
  Query: {}
  S3SignedPath: {
    // root type
    signedRequest: string // String!
    url: string // String!
  }
  SearchItem: {
    // root type
    author?: string | null // String
    id?: string | null // String
    title?: string | null // String
    type?: string | null // String
  }
  Section: {
    // root type
    collections: NexusGenRootTypes['Collection'][] // [Collection!]!
    createdAt: NexusGenScalars['DateTime'] // DateTime!
    id: string // String!
    index: number // Int!
    isExpanded: boolean // Boolean!
    name?: string | null // String
    slug: string // String!
  }
  User: {
    // root type
    authUserId?: string | null // String
    biography?: string | null // String
    firstname: string // String!
    github?: string | null // String
    id: string // String!
    label?: string | null // String
    linkedin?: string | null // String
    mail?: string | null // String
    pictureUrl: string // String!
    sections: NexusGenRootTypes['Section'][] // [Section!]!
    slug: string // String!
    website?: string | null // String
    youtube?: string | null // String
  }
}

export interface NexusGenInterfaces {}

export interface NexusGenUnions {}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes &
  NexusGenScalars &
  NexusGenEnums

export interface NexusGenFieldTypes {
  Collection: {
    // field return type
    createdAt: NexusGenScalars['DateTime'] // DateTime!
    detail: string | null // String
    id: string // String!
    isDeleted: boolean // Boolean!
    items: NexusGenRootTypes['Item'][] // [Item!]!
    name: string | null // String
    owner: NexusGenRootTypes['User'] // User!
    section: NexusGenRootTypes['Section'] // Section!
    slug: string // String!
    updatedAt: NexusGenScalars['DateTime'] // DateTime!
  }
  Inbox: {
    // field return type
    count: number | null // Int
    id: string | null // String
    items: Array<NexusGenRootTypes['Item'] | null> | null // [Item]
  }
  Item: {
    // field return type
    author: string | null // String
    comment: string | null // String
    createdAt: NexusGenScalars['DateTime'] // DateTime!
    description: string | null // String
    id: string // String!
    imageUrl: string | null // String
    isDeleted: boolean // Boolean!
    meta: string | null // String
    position: number // Int!
    productUrl: string | null // String
    provider: string | null // String
    title: string // String!
    type: NexusGenEnums['ItemType'] // ItemType!
  }
  Mutation: {
    // field return type
    changeItemPosition: NexusGenRootTypes['Item'][] // [Item!]!
    createEmptyCollection: NexusGenRootTypes['Collection'] | null // Collection
    createEmptySection: NexusGenRootTypes['Section'] | null // Section
    createItemFromSearch: NexusGenRootTypes['Item'] // Item!
    createItemFromUrl: NexusGenRootTypes['Item'] // Item!
    createNewUser: NexusGenRootTypes['User'] | null // User
    createOneUser: NexusGenRootTypes['User'] // User!
    signS3: NexusGenRootTypes['S3SignedPath'] | null // S3SignedPath
    updateOneCollection: NexusGenRootTypes['Collection'] | null // Collection
    updateOneItem: NexusGenRootTypes['Item'] | null // Item
    updateOneSection: NexusGenRootTypes['Section'] | null // Section
    updateOneUser: NexusGenRootTypes['User'] | null // User
  }
  Query: {
    // field return type
    collection: NexusGenRootTypes['Collection'] | null // Collection
    collections: NexusGenRootTypes['Collection'][] // [Collection!]!
    inbox: NexusGenRootTypes['Inbox'] | null // Inbox
    items: NexusGenRootTypes['Item'][] // [Item!]!
    search: NexusGenRootTypes['SearchItem'][] // [SearchItem!]!
    section: NexusGenRootTypes['Section'] | null // Section
    sections: NexusGenRootTypes['Section'][] // [Section!]!
    user: NexusGenRootTypes['User'] | null // User
  }
  S3SignedPath: {
    // field return type
    signedRequest: string // String!
    url: string // String!
  }
  SearchItem: {
    // field return type
    author: string | null // String
    id: string | null // String
    title: string | null // String
    type: string | null // String
  }
  Section: {
    // field return type
    collections: NexusGenRootTypes['Collection'][] // [Collection!]!
    createdAt: NexusGenScalars['DateTime'] // DateTime!
    id: string // String!
    index: number // Int!
    isExpanded: boolean // Boolean!
    name: string | null // String
    slug: string // String!
  }
  User: {
    // field return type
    authUserId: string | null // String
    biography: string | null // String
    firstname: string // String!
    github: string | null // String
    id: string // String!
    label: string | null // String
    linkedin: string | null // String
    mail: string | null // String
    pictureUrl: string // String!
    sections: NexusGenRootTypes['Section'][] // [Section!]!
    slug: string // String!
    website: string | null // String
    youtube: string | null // String
  }
}

export interface NexusGenFieldTypeNames {
  Collection: {
    // field return type name
    createdAt: 'DateTime'
    detail: 'String'
    id: 'String'
    isDeleted: 'Boolean'
    items: 'Item'
    name: 'String'
    owner: 'User'
    section: 'Section'
    slug: 'String'
    updatedAt: 'DateTime'
  }
  Inbox: {
    // field return type name
    count: 'Int'
    id: 'String'
    items: 'Item'
  }
  Item: {
    // field return type name
    author: 'String'
    comment: 'String'
    createdAt: 'DateTime'
    description: 'String'
    id: 'String'
    imageUrl: 'String'
    isDeleted: 'Boolean'
    meta: 'String'
    position: 'Int'
    productUrl: 'String'
    provider: 'String'
    title: 'String'
    type: 'ItemType'
  }
  Mutation: {
    // field return type name
    changeItemPosition: 'Item'
    createEmptyCollection: 'Collection'
    createEmptySection: 'Section'
    createItemFromSearch: 'Item'
    createItemFromUrl: 'Item'
    createNewUser: 'User'
    createOneUser: 'User'
    signS3: 'S3SignedPath'
    updateOneCollection: 'Collection'
    updateOneItem: 'Item'
    updateOneSection: 'Section'
    updateOneUser: 'User'
  }
  Query: {
    // field return type name
    collection: 'Collection'
    collections: 'Collection'
    inbox: 'Inbox'
    items: 'Item'
    search: 'SearchItem'
    section: 'Section'
    sections: 'Section'
    user: 'User'
  }
  S3SignedPath: {
    // field return type name
    signedRequest: 'String'
    url: 'String'
  }
  SearchItem: {
    // field return type name
    author: 'String'
    id: 'String'
    title: 'String'
    type: 'String'
  }
  Section: {
    // field return type name
    collections: 'Collection'
    createdAt: 'DateTime'
    id: 'String'
    index: 'Int'
    isExpanded: 'Boolean'
    name: 'String'
    slug: 'String'
  }
  User: {
    // field return type name
    authUserId: 'String'
    biography: 'String'
    firstname: 'String'
    github: 'String'
    id: 'String'
    label: 'String'
    linkedin: 'String'
    mail: 'String'
    pictureUrl: 'String'
    sections: 'Section'
    slug: 'String'
    website: 'String'
    youtube: 'String'
  }
}

export interface NexusGenArgTypes {
  Collection: {
    items: {
      // args
      after?: NexusGenInputs['ItemWhereUniqueInput'] | null // ItemWhereUniqueInput
      before?: NexusGenInputs['ItemWhereUniqueInput'] | null // ItemWhereUniqueInput
      first?: number | null // Int
      last?: number | null // Int
      orderBy?: NexusGenInputs['CollectionItemsOrderByInput'] | null // CollectionItemsOrderByInput
      skip?: number | null // Int
      where?: NexusGenInputs['CollectionItemsWhereInput'] | null // CollectionItemsWhereInput
    }
  }
  Mutation: {
    changeItemPosition: {
      // args
      collectionId: string // ID!
      newIndex: number // Int!
      oldIndex: number // Int!
    }
    createEmptyCollection: {
      // args
      sectionId: string // ID!
    }
    createItemFromSearch: {
      // args
      collectionId?: string | null // String
      id: string // String!
      inbox?: boolean | null // Boolean
      kind: string // String!
    }
    createItemFromUrl: {
      // args
      collectionId?: string | null // String
      inbox?: boolean | null // Boolean
      url: string // String!
    }
    createNewUser: {
      // args
      authUserId: string // String!
      firstname: string // String!
      pictureUrl: string // String!
      slug: string // String!
    }
    createOneUser: {
      // args
      data: NexusGenInputs['UserCreateInput'] // UserCreateInput!
    }
    signS3: {
      // args
      fileName: string // String!
      fileType: string // String!
    }
    updateOneCollection: {
      // args
      data: NexusGenInputs['CollectionUpdateInput'] // CollectionUpdateInput!
      where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
    }
    updateOneItem: {
      // args
      data: NexusGenInputs['ItemUpdateInput'] // ItemUpdateInput!
      where: NexusGenInputs['ItemWhereUniqueInput'] // ItemWhereUniqueInput!
    }
    updateOneSection: {
      // args
      data: NexusGenInputs['SectionUpdateInput'] // SectionUpdateInput!
      where: NexusGenInputs['SectionWhereUniqueInput'] // SectionWhereUniqueInput!
    }
    updateOneUser: {
      // args
      data: NexusGenInputs['UserUpdateInput'] // UserUpdateInput!
      where: NexusGenInputs['UserWhereUniqueInput'] // UserWhereUniqueInput!
    }
  }
  Query: {
    collection: {
      // args
      where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
    }
    collections: {
      // args
      after?: NexusGenInputs['CollectionWhereUniqueInput'] | null // CollectionWhereUniqueInput
      before?: NexusGenInputs['CollectionWhereUniqueInput'] | null // CollectionWhereUniqueInput
      first?: number | null // Int
      last?: number | null // Int
      orderBy?: NexusGenInputs['QueryCollectionsOrderByInput'] | null // QueryCollectionsOrderByInput
      skip?: number | null // Int
      where?: NexusGenInputs['QueryCollectionsWhereInput'] | null // QueryCollectionsWhereInput
    }
    items: {
      // args
      after?: NexusGenInputs['ItemWhereUniqueInput'] | null // ItemWhereUniqueInput
      before?: NexusGenInputs['ItemWhereUniqueInput'] | null // ItemWhereUniqueInput
      first?: number | null // Int
      last?: number | null // Int
      orderBy?: NexusGenInputs['QueryItemsOrderByInput'] | null // QueryItemsOrderByInput
      skip?: number | null // Int
      where?: NexusGenInputs['QueryItemsWhereInput'] | null // QueryItemsWhereInput
    }
    search: {
      // args
      kind: string // String!
      q: string // String!
    }
    section: {
      // args
      where: NexusGenInputs['SectionWhereUniqueInput'] // SectionWhereUniqueInput!
    }
    sections: {
      // args
      after?: NexusGenInputs['SectionWhereUniqueInput'] | null // SectionWhereUniqueInput
      before?: NexusGenInputs['SectionWhereUniqueInput'] | null // SectionWhereUniqueInput
      first?: number | null // Int
      last?: number | null // Int
      orderBy?: NexusGenInputs['QuerySectionsOrderByInput'] | null // QuerySectionsOrderByInput
      skip?: number | null // Int
      where?: NexusGenInputs['QuerySectionsWhereInput'] | null // QuerySectionsWhereInput
    }
    user: {
      // args
      where: NexusGenInputs['UserWhereUniqueInput'] // UserWhereUniqueInput!
    }
  }
  Section: {
    collections: {
      // args
      after?: NexusGenInputs['CollectionWhereUniqueInput'] | null // CollectionWhereUniqueInput
      before?: NexusGenInputs['CollectionWhereUniqueInput'] | null // CollectionWhereUniqueInput
      first?: number | null // Int
      last?: number | null // Int
      orderBy?: NexusGenInputs['SectionCollectionsOrderByInput'] | null // SectionCollectionsOrderByInput
      skip?: number | null // Int
      where?: NexusGenInputs['SectionCollectionsWhereInput'] | null // SectionCollectionsWhereInput
    }
  }
  User: {
    sections: {
      // args
      after?: NexusGenInputs['SectionWhereUniqueInput'] | null // SectionWhereUniqueInput
      before?: NexusGenInputs['SectionWhereUniqueInput'] | null // SectionWhereUniqueInput
      first?: number | null // Int
      last?: number | null // Int
      skip?: number | null // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {}

export interface NexusGenTypeInterfaces {}

export type NexusGenObjectNames = keyof NexusGenObjects

export type NexusGenInputNames = keyof NexusGenInputs

export type NexusGenEnumNames = keyof NexusGenEnums

export type NexusGenInterfaceNames = never

export type NexusGenScalarNames = keyof NexusGenScalars

export type NexusGenUnionNames = never

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never

export type NexusGenAbstractsUsingStrategyResolveType = never

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context
  inputTypes: NexusGenInputs
  rootTypes: NexusGenRootTypes
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars
  argTypes: NexusGenArgTypes
  fieldTypes: NexusGenFieldTypes
  fieldTypeNames: NexusGenFieldTypeNames
  allTypes: NexusGenAllTypes
  typeInterfaces: NexusGenTypeInterfaces
  objectNames: NexusGenObjectNames
  inputNames: NexusGenInputNames
  enumNames: NexusGenEnumNames
  interfaceNames: NexusGenInterfaceNames
  scalarNames: NexusGenScalarNames
  unionNames: NexusGenUnionNames
  allInputTypes:
    | NexusGenTypes['inputNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['scalarNames']
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames']
  allNamedTypes:
    | NexusGenTypes['allInputTypes']
    | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames']
  abstractTypeMembers: NexusGenAbstractTypeMembers
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType
  features: NexusGenFeaturesConfig
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {}
  interface NexusGenPluginInputFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {}
  interface NexusGenPluginSchemaConfig {}
  interface NexusGenPluginArgConfig {}
}
